version: "3"
services:
  # Micro-service de management des hôpitaux / spécialités
  ms-hospital-management:
    image: yvalero/ms-hospital-management:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "9000:9000"
    networks:
      - my-network

  # Micro-service de management des urgences
  ms-emergency-management:
    image: yvalero/ms-emergency-management:latest
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network

  # Micro-service de calcul de distance 
  ms-emergency-dispatcher:
    image: yvalero/ms-emergency-dispatcher:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network

  # Front-end
  medhead-front:
    image: yvalero/medhead-front:latest
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - ms-hospital-management
      - ms-emergency-management
      - ms-emergency-dispatcher
