name: Medhead-app workflow
on:
  push:
    branches: [ main ]

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./medhead-front
        run: npm install

      - name: Run tests
        run: npm run e2e

      - name: Check for changes in ms-hospital-management
        id: check_mshm
        run: |
          if [[ -n $(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ms-hospital-management/) ]]; then
            echo "Changes detected in mshm."
            echo "::set-output name=changed::true"
          else
            echo "No changes detected in mshm."
            echo "::set-output name=changed::false"
          fi

      - name: Build and Test MSHM
        if: ${{ steps.check_mshm.outputs.changed == 'true' }}
        working-directory: ./ms-hospital-management
        run: |
          ./mvnw clean package
          ./mvnw test
            
      - name: Publish Docker Image MSMH
        if: ${{ steps.check_mshm.outputs.changed == 'true' }}
        working-directory: ./ms-hospital-management
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t yvalero/ms-hospital-management:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/ms-hospital-management:latest
        
