name: Medhead-app workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

  check-changes:  
    runs-on: ubuntu-latest
    needs: project-build
    outputs:
      CHANGED_MSHM: ${{ steps.check_mshm.outputs.CHANGED_MSHM }}
      CHANGED_MSEM: ${{ steps.check_msem.outputs.CHANGED_MSEM }}
      CHANGED_MSED: ${{ steps.check_msed.outputs.CHANGED_MSED }}
      CHANGED_MF: ${{ steps.check_mf.outputs.CHANGED_MF }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # MS-hospital-management
      - name: Check for changes in ms-hospital-management
        id: check_mshm
        run: |
          if [[ -n $(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ms-hospital-management/) ]]; then
            echo "Changes detected in mshm."
            echo "CHANGED_MSHM=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected in mshm."
          fi
 
      # MS-emergency-management
      - name: Check for changes in ms-emergency-management
        id: check_msem
        run: |
          if [[ -n $(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ms-emergency-management/) ]]; then
            echo "Changes detected in msem."
            echo "CHANGED_MSEM=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected in msem."
          fi

      # MS-emergency-dispatcher
      - name: Check for changes in ms-emergency-dispatcher
        id: check_msed
        run: |
          if [[ -n $(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ms-emergency-dispatcher/) ]]; then
            echo "Changes detected in msed."
            echo "CHANGED_MSED=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected in msed."
          fi

      # MS-medhead-front
      - name: Check for changes in medhead-front
        id: check_mf
        run: |
          if [[ -n $(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} -- medhead-front/) ]]; then
            echo "Changes detected in mf."
            echo "CHANGED_MF=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected in mf."
          fi

  tests:
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies for medhead-front
        working-directory: ./medhead-front
        run: npm install

      # MS-hospital-management
      - name: Build and Test MSHM
        working-directory: ./ms-hospital-management
        run: |
          ./mvnw clean package
          ./mvnw test

      # MS-emergency-management
      - name: Build and Test MSEM
        working-directory: ./ms-emergency-management
        run: |
          ./mvnw clean package
          ./mvnw test

      # MS-emergency-dispatcher
      - name: Build and Test MSED
        working-directory: ./ms-emergency-dispatcher
        run: |
          ./mvnw clean package
          ./mvnw test 

      - name: Start MS-hospital-management
        working-directory: ./ms-hospital-management
        run: |
          ./mvnw clean install
          ./mvnw spring-boot:run &

      - name: Start MS-emergency-management
        working-directory: ./ms-emergency-management
        run: ./mvnw spring-boot:run &

      - name: Start MS-emergency-dispatcher
        working-directory: ./ms-emergency-dispatcher
        run: ./mvnw spring-boot:run &

      - name: Build Angular App
        working-directory: ./medhead-front
        run: npm run start & 
  
      - name: Run E2E Tests with Xvfb
        working-directory: ./medhead-front/e2e
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node bookBed.js           

  publish:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    needs: [check-changes, tests]
    env:
      CHANGED_MSHM: ${{ needs.check-changes.outputs.CHANGED_MSHM }}
      CHANGED_MSEM: ${{ needs.check-changes.outputs.CHANGED_MSEM }}
      CHANGED_MSED: ${{ needs.check-changes.outputs.CHANGED_MSED }}
      CHANGED_MF: ${{ needs.check-changes.outputs.CHANGED_MF }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: test Env Vars
        run: |
          echo "changed mshm ${{ needs.check-changes.outputs.CHANGED_MSHM }}"
          echo "changed mshm $CHANGED_MSHM"
          echo $DOCKERHUB_USERNAME
          echo "changed msem ${{ needs.check-changes.outputs.CHANGED_MSEM }}"
          echo "changed msed ${{ needs.check-changes.outputs.CHANGED_MSED }}"

      - name: Publish Docker Image MSMH
        if: ${{ env.CHANGED_MSHM == 'true' }}
        working-directory: ./ms-hospital-management
        run: |
          docker build -t yvalero/ms-hospital-management:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/ms-hospital-management:latest

      - name: Publish Docker Image MSEM
        if: ${{ env.CHANGED_MSEM == 'true' }}
        working-directory: ./ms-emergency-management
        run: |
          docker build -t yvalero/ms-emergency-management:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/ms-emergency-management:latest

      - name: Publish Docker Image MSED
        if: ${{ env.CHANGED_MSED == 'true' }}
        working-directory: ./ms-emergency-dispatcher
        run: |
          docker build -t yvalero/ms-emergency-dispatcher:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/ms-emergency-dispatcher:latest

      - name: Publish Docker Image Medhead-front
        if: ${{ env.CHANGED_MF == 'true' }}
        working-directory: ./medhead-front
        run: |
          docker build -t yvalero/medhead-front:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/medhead-front:latest
