name: Medhead-app workflow
on:
  push:
    branches: [ main ]

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test MSH
        if: contains(github.event.head_commit.modified, 'ms-hospital-management2/')
        working-directory: ./ms-hospital-management2
        run: |
          ./mvnw clean package
          ./mvnw test
            
      - name: Publish Docker Image MSH
        if: contains(github.event.head_commit.modified, 'ms-hospital-management2/')
        working-directory: ./ms-hospital-management2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t yvalero/ms-hospital-management2:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/ms-hospital-management2:latest
        
