name: Medhead-app workflow
on:
  push:
    branches: [ main ]

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check for changes in msh2
        id: check_msh2
        run: |
          if [[ -n $(git --no-pager diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ms-hospital-management2/) ]]; then
            echo "Changes detected in msh2."
            echo "::set-output name=changed::true"
          else
            echo "No changes detected in msh2."
            echo "::set-output name=changed::false"
          fi

      - name: Build and Test MSH
        if: ${{ steps.check_msh2.outputs.changed == 'true' }}
        working-directory: ./ms-hospital-management2
        run: |
          ./mvnw clean package
          ./mvnw test
            
      - name: Publish Docker Image MSH
        if: ${{ steps.check_msh2.outputs.changed == 'true' }}
        working-directory: ./ms-hospital-management2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t yvalero/ms-hospital-management2:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker push yvalero/ms-hospital-management2:latest
        
